print("hello, welcome to roll number finder")
names = []

n1 = input("enter the name of the first person       ")
n2 = input("enter the name of the second person      ")
n3 = input("enter the name of the 3rd person         ")
n4 = input("enter the name of the 4th person         ")
n5 = input("enter the name of the 5th person         ")
n6 = input("enter the name of the 6th person         ")
n7 = input("enter the name of the 7th person         ")
n8 = input("enter the name of the 8th person         ")
n9 = input("enter the name of the 9th person         ")
n10 = input("enter the name of the 10th person         ")
n11 = input("enter the name of the 11th person         ")
n12 = input("enter the name of the 12th person         ")
n13 = input("enter the name of the 13th person         ")
n14 = input("enter the name of the 14th person         ")
n15 = input("enter the name of the 15th person         ")
n16 = input("enter the name of the 16th person         ")
n17 = input("enter the name of the 17th person         ")
n18 = input("enter the name of the 18th person         ")
n19 = input("enter the name of the 19th person         ")
n20 = input("enter the name of the 20th person         ")
names.append(f"{n1}")
names.append(f"{n2}")
names.append(f"{n3}")
names.append(f"{n4}")
names.append(f"{n5}")
names.append(f"{n6}")
names.append(f"{n7}")
names.append(f"{n8}")
names.append(f"{n9}")
names.append(f"{n10}")
names.append(f"{n11}")
names.append(f"{n12}")
names.append(f"{n13}")
names.append(f"{n14}")
names.append(f"{n15}")
names.append(f"{n16}")
names.append(f"{n17}")
names.append(f"{n18}")
names.append(f"{n19}")
names.append(f"{n20}")
names.sort()
print(f"{names[0]} is roll no; 1 ")
print(f"{names[1]} is roll no; 2 ")
print(f"{names[2]} is roll no; 3 ")
print(f"{names[3]} is roll no; 4 ")
print(f"{names[4]} is roll no; 5 ")
print(f"{names[5]} is roll no; 6 ")
print(f"{names[6]} is roll no; 7 ")
print(f"{names[7]} is roll no; 8 ")
print(f"{names[8]} is roll no; 9 ")
print(f"{names[9]} is roll no; 10 ")
print(f"{names[10]} is roll no; 11  ")
print(f"{names[11]} is roll no; 12 ")
print(f"{names[12]} is roll no; 13 ")
print(f"{names[13]} is roll no; 14 ")
print(f"{names[14]} is roll no; 15 ")
print(f"{names[15]} is roll no; 16 ")
print(f"{names[16]} is roll no; 17 ")
print(f"{names[17]} is roll no; 18 ")
print(f"{names[18]} is roll no; 19 ")
print(f"{names[19]} is roll no; 20 ")